services:
  library:
    image: niknikbox/library
    restart: always
    ports:
      - "3000:3000"
    # networks:
    #   - front-tier
    #   - back-tier
    # configs:
    #   - httpd-config
    # secrets:
    #   - server-certificate

  counter:
    image: niknikbox/library_counter
    restart: always

    # volumes:
    #   - db-data:/etc/data
    # networks:
    #   - back-tier
# volumes:
# db-data:
# driver: flocker
# driver_opts:
# size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}
