# version: "3.1"

# services:
#   mongo:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
# ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

library:
  image: niknikbox/library
  restart: always
  ports:
    - "3000:3000"
  # networks:
  #   - front-tier
  #   - back-tier
  # configs:
  #   - httpd-config
  # secrets:
  #   - server-certificate

counter:
  image: niknikbox/counter
  restart: always

  # volumes:
  #   - db-data:/etc/data
  # networks:
  #   - back-tier
# volumes:
# db-data:
# driver: flocker
# driver_opts:
# size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}
